name: 001 Build and Publish Docker Image

on:
  workflow_call:
    inputs:
     image_name:
        required: true
        type: string
     latest:   
        required: true
        type: boolean
     DOCKERREPONAME:
        required: true
        type: string
     TAG:
        required: true
        type: string
    secrets:
        DOCKER_USER:
          required: true
        DOCKER_PASSWORD:
          required: true
env:
  HEROKU_REGISTRY_URL: registry.heroku.com
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
     # - name: Docker Setup Buildx
     #   uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }} 
      
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
         flavor: |
           latest=${{inputs.latest}}
         images: 
          ${{inputs.image_name}}
                
      - name: Build the Docker image
        uses: docker/build-push-action@v3.1.1
        with:
         push: true
         tags: ${{ steps.docker_meta.outputs.tags }}
         labels: ${{ steps.docker_meta.outputs.labels }}
