name: 001 Create and Publish Docker Image

on:
  workflow_call:
    inputs:
     image_name:
        required: true
        type: string
     latest:   
        required: true
        type: boolean
     DOCKERREPONAME:
        required: true
        type: string
     TAG:
        required: true
        type: string
     APPNAME:
        required: true
        type: string
    secrets:
        DOCKER_USER:
          required: true
        DOCKER_PASSWORD:
          required: true
        HEROKU_USERNAME:
          required: true
        HEROKU_API_KEY: 
          required: true
env:
  HEROKU_REGISTRY_URL: registry.heroku.com
          
jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
     # - name: Docker Setup Buildx
     #   uses: docker/setup-buildx-action@v2.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }} 
      
      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
         flavor: |
           latest=${{inputs.latest}}
         images: 
          ${{inputs.image_name}}
          
          
      - name: Build the Docker image
        uses: docker/build-push-action@v3.1.1
        with:
         push: true
         tags: ${{ steps.docker_meta.outputs.tags }}
         labels: ${{ steps.docker_meta.outputs.labels }}
      
      - name: Login to heroku container
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_email: ${{secrets.HEROKU_USERNAME}}
         docker_heroku_process_type: web
         region: Europe
         justlogin: true
      
     # - name: Deploy to heroku
     #   run: |
     #      docker login --username=_ --password ${{secrets.HEROKU_API_KEY}} $HEROKU_REGISTRY_URL
     #      docker tag $TAG registry.heroku.com/$APPNAME/web
     #      docker push $HEROKU_REGISTRY_URL/$APPNAME/web
     #      heroku container:release web -a $APPNAME
