name: 002 Deploy image to Heroku

on:
  workflow_call:
    inputs:
       APPNAME:
         required: true
         type: string
       TAG:
         required: true
         type: string
       
    secrets:
        DOCKER_USER:
          required: true
        DOCKER_PASSWORD:
          required: true
        HEROKU_API_KEY: 
          required: true
        HEROKU_USERNAME:
          required: true
        
env:
  HEROKU_REGISTRY_URL: registry.heroku.com
          
jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v3
            
      - name: Login to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
         username: ${{ secrets.DOCKER_USER }}
         password: ${{ secrets.DOCKER_PASSWORD }} 
      
      - name: Pull image
        run:
          docker pull $TAG
      
      - name: Login to heroku container
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_email: ${{secrets.HEROKU_USERNAME}}
         docker_heroku_process_type: web
         region: Europe
         justlogin: true
      
      - name: Deploy to heroku
        run: |
           docker login --username=_ --password ${{secrets.HEROKU_API_KEY}} $HEROKU_REGISTRY_URL
           docker tag $TAG registry.heroku.com/$APPNAME/web
           docker push $HEROKU_REGISTRY_URL/$APPNAME/web
           heroku container:release web -a $APPNAME
