name: Deploy to Staging

on:
  workflow_dispatch:
  release:
       types: [published]

  
jobs:
  Build:
      uses: plazo1975/mvcdotnetdocker/.github/workflows/001_BuildAndPublishDockerImage.yml@develop
      with:
       image_name: plazo/mvcdotnetdocker
       latest: false
       DOCKERREPONAME: plazo/mvcdotnetdocker
       ExtraTag: plazo/mvcdotnetdocker:main
      secrets:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       
  DeployAcc:
       needs: Build
       uses: plazo1975/mvcdotnetdocker/.github/workflows/002_DeployImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-acc
        TAG: plazo/mvcdotnetdocker:main
       secrets:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
   
  ReleaseAcc:
       needs: DeployAcc
       uses: plazo1975/mvcdotnetdocker/.github/workflows/003_ReleaseImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-acc
       secrets:
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}} 
