name: Deploy to production

on:
  workflow_dispatch:
  
jobs:
     
  DeployPrd:
       uses: plazo1975/mvcdotnetdocker/.github/workflows/002_DeployImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-prd
        TAG: plazo/mvcdotnetdocker:main
       secrets:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
   
  ReleaseAcc:
       needs: DeployPrd
       uses: plazo1975/mvcdotnetdocker/.github/workflows/003_ReleaseImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-prd
       secrets:
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}} 
