name: Deploy to development

on:
  workflow_dispatch:
  #push:
  # branches:
  #   - 'develop'
  
jobs:
  Build:
      uses: plazo1975/mvcdotnetdocker/.github/workflows/001_BuildAndPublishDockerImage.yml@develop
      with:
       image_name: plazo/mvcdotnetdocker
       latest: true
       DOCKERREPONAME: plazo/mvcdotnetdocker
      secrets:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
       
       
  Deploy:
       needs: Build
       uses: plazo1975/mvcdotnetdocker/.github/workflows/002_DeployImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-dev
        TAG: plazo/mvcdotnetdocker:develop
       secrets:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}
    
  Release:
       needs: Deploy
       uses: plazo1975/mvcdotnetdocker/.github/workflows/003_ReleaseImageToHeroku.yml@develop
       with:
        APPNAME: mvcdotnetdocker-dev
       secrets:
        HEROKU_API_KEY : ${{secrets.HEROKU_API_KEY}}
        HEROKU_USERNAME: ${{secrets.HEROKU_USERNAME}}      
