name: Docker TEST Customer
on:
     release:
       types: [published]
  
     workflow_dispatch:

env:
  APPNAME: mvcdotnetdocker-tst-customer
  TAG: plazo/mvcdotnetdocker
  DOCKERREPONAME: plazo/mvcdotnetdocker
  HEROKU_REGISTRY_URL: registry.heroku.com
  HEROKU_TOKEN : ${{secrets.HEROKU_API_KEY}}
  

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
     
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASSWORD }}      

    
    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v4.0.1
      with:
       flavor: |
          latest=false
       images: 
          plazo/mvcdotnetdocker
       
       env: DTAG={{tag}}
       
    - name: Build the Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
     
  
    - name: Login to heroku container
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_USERNAME}}
        docker_heroku_process_type: web
        region: Europe
        justlogin: true
    
    - name: Deploy to heroku
      run: |
           docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
           docker tag $TAG:$DTAG registry.heroku.com/$APPNAME/web
           docker push $HEROKU_REGISTRY_URL/$APPNAME/web
           heroku container:release web -a $APPNAME
