name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASSWORD }}
                 
    
    
    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: plazo/mvcdotnetdocker
        flavor:
          latest=false
        tags:
           #type=raw, value=04
           #type=raw, value=latest, enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
           #type=ref, event=pr
           #type=ref, event=branch
           #type=semver, pattern={{version}}
           # branch event
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
        
    - name: Build the Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    
    
    
    #- name: Push to docker hub
    #  run: |
    #     docker push --all-tags plazo/mvcdotnetdocker
    
    
    #- name: Login to heroku container
    #  uses: AkhileshNS/heroku-deploy@v3.12.12
    #  with:
    #    heroku_api_key: ${{secrets.HEROKU_API_KEY}}
    #    heroku_email: ${{secrets.HEROKU_USERNAME}}
    #    heroku_app_name: mvcdotnetdocker
    #    docker_heroku_process_type: web
    #    region: Europe
    #    justlogin: true
    #- name: Deploy to heroku
    #  env:
    #    HEROKU_REGISTRY_URL: registry.heroku.com
    #    HEROKU_TOKEN : ${{secrets.HEROKU_API_KEY}}
    #  run: |
    #      docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
    #     
    #      heroku container:push web -a mvcdotnetdocker
    #      heroku container:release web -a mvcdotnetdocker
      
        

