name: Docker DEV

on:
  push:
    branches:
      - 'dev'
   # tags:
   #   - 'v*'
  #pull_request:
  #  branches:
  #    - 'master'

  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.0.0
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_PASSWORD }}      
    
    - name: Docker Meta
      id: docker_meta
      uses: docker/metadata-action@v4.0.1
      with:
        images: plazo/mvcdotnetdocker
  
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        #tags: develop
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
        
    - name: Login to heroku container
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_USERNAME}}
        heroku_app_name: mvcdotnetdocker-dev
        docker_heroku_process_type: web
        region: Europe
        justlogin: true
    
    - name: Deploy to heroku
      env:
        HEROKU_REGISTRY_URL: registry.heroku.com
        HEROKU_TOKEN : ${{secrets.HEROKU_API_KEY}}
      run: |
           docker login --username=_ --password $HEROKU_TOKEN $HEROKU_REGISTRY_URL
           docker tag plazo/mvcdotnetdocker registry.heroku.com/plazo/mvcdotnetdocker-dev/web
           heroku container:push web -a mvcdotnetdocker-dev
           heroku container:release web -a mvcdotnetdocker-dev
