name: Manual customer1 ACC

on:
  workflow_dispatch

env:
  SOURCE: mvcdotnetdocker-tst-customer
  TARGET: mvcdotnetdocker-acc
jobs:
  Deploy_ACC:
    runs-on: ubuntu-latest
    environment: Staging Customer1

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Deploy to Staging Customer1
      uses: NikitaGlukhi/heroku-pipelines-promoting@v2
      with:
         heroku_api_key: ${{secrets.HEROKU_API_KEY}}
         heroku_email: ${{secrets.HEROKU_USERNAME}}
         heroku_app_name: $SOURCE
         heroku_promote_to_app: $TARGET
